CREATE TABLE admins(id uuid PRIMARY KEY,username text NOT NULL UNIQUE,password_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE members(id uuid PRIMARY KEY,full_name text NOT NULL,national_id_digest text NOT NULL UNIQUE,national_id_encrypted text NOT NULL,national_id_last4 text NOT NULL,phone text NOT NULL,phone_verified_at timestamptz,identity_version integer NOT NULL DEFAULT 1,age_group text NOT NULL CHECK(age_group IN ('adult','child')),preferred_language text NOT NULL CHECK(preferred_language IN ('ar','en')),notes text NOT NULL DEFAULT '',access_enabled boolean NOT NULL DEFAULT true,updates_consent boolean NOT NULL DEFAULT false,marketing_consent boolean NOT NULL DEFAULT false,archived_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE plans(id text PRIMARY KEY,data jsonb NOT NULL,archived_at timestamptz);
CREATE TABLE sports(id text PRIMARY KEY,data jsonb NOT NULL,archived_at timestamptz);
CREATE TABLE coaches(id text PRIMARY KEY,data jsonb NOT NULL,archived_at timestamptz);
CREATE TABLE offers(id text PRIMARY KEY,data jsonb NOT NULL,archived_at timestamptz);
CREATE TABLE site_settings(id integer PRIMARY KEY CHECK(id=1),data jsonb NOT NULL);
CREATE TABLE content_revisions(revision serial PRIMARY KEY,blocks jsonb NOT NULL,published boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX one_published_revision ON content_revisions(published) WHERE published;
CREATE TABLE classes(id uuid PRIMARY KEY,data jsonb NOT NULL);
CREATE INDEX classes_date ON classes((data->>'date'));
CREATE TABLE memberships(id uuid PRIMARY KEY,member_id uuid NOT NULL REFERENCES members(id),plan_id text NOT NULL REFERENCES plans(id),plan_snapshot jsonb NOT NULL,start_date date NOT NULL,end_date date NOT NULL,sports text[] NOT NULL,suspended boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,current boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),CHECK(end_date>=start_date));
CREATE UNIQUE INDEX current_membership ON memberships(member_id) WHERE current;
CREATE TABLE membership_operations(id uuid PRIMARY KEY,member_id uuid NOT NULL REFERENCES members(id),idempotency_key text UNIQUE,request_digest text,action text NOT NULL,before_data jsonb,after_data jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_events(id uuid PRIMARY KEY,member_id uuid REFERENCES members(id),actor text NOT NULL,action text NOT NULL,details jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions(token_digest text PRIMARY KEY,kind text NOT NULL CHECK(kind IN ('admin','member')),actor_id uuid NOT NULL,identity_version integer,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX sessions_actor ON sessions(actor_id);
CREATE TABLE login_challenges(id uuid PRIMARY KEY,member_id uuid NOT NULL REFERENCES members(id),phone text NOT NULL,identity_version integer NOT NULL,code_digest text NOT NULL,attempts integer NOT NULL DEFAULT 0,expires_at timestamptz NOT NULL,consumed_at timestamptz,delivery_status text NOT NULL DEFAULT 'sending',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE rate_limits(key text PRIMARY KEY,window_start timestamptz NOT NULL,count integer NOT NULL);
CREATE TABLE announcements(id uuid PRIMARY KEY,title jsonb NOT NULL,body jsonb NOT NULL,target text NOT NULL,member_id uuid REFERENCES members(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE announcement_reads(member_id uuid NOT NULL REFERENCES members(id),announcement_id uuid NOT NULL REFERENCES announcements(id),PRIMARY KEY(member_id,announcement_id));
CREATE TABLE outbox(id uuid PRIMARY KEY,member_id uuid REFERENCES members(id),event text NOT NULL,payload jsonb NOT NULL,category text NOT NULL CHECK(category IN ('authentication','utility','marketing')),status text NOT NULL DEFAULT 'queued',attempts integer NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),provider_id text UNIQUE,claim_token uuid,claimed_at timestamptz,updated_at timestamptz NOT NULL DEFAULT now(),event_key text UNIQUE,error text,created_at timestamptz NOT NULL DEFAULT now(),dedupe_key text UNIQUE);
CREATE INDEX outbox_queue ON outbox(next_attempt_at) WHERE status='queued';
CREATE TABLE schedule_copies(idempotency_key text PRIMARY KEY,request_digest text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE consent_events(id uuid PRIMARY KEY,member_id uuid NOT NULL REFERENCES members(id),category text NOT NULL,allowed boolean NOT NULL,source text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE media(id uuid PRIMARY KEY,object_key text NOT NULL UNIQUE,url text NOT NULL,mime text NOT NULL,width integer,height integer,created_at timestamptz NOT NULL DEFAULT now());
